repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10.10
-   repo: local
    hooks:
    -   id: mkdocs
        name: mkdocs-build
        entry: mkdocs build
        language: system
        pass_filenames: false
        types: [python]