site_name: TVTime Scrapy API Docs

repo_url: https://github.com/giraycoskun/tvtime-scrapy-api
repo_name: tvtime-scrapy-api

theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']  # search packages in the src folder
          options:
            docstring_style: "google"
            show_root_heading: true
            show_if_no_docstring: true
  - swagger-ui-tag:
      tryItOutEnabled: True

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: ["."]
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html

nav:
  - Home: 
    - index.md
    - Getting Started: getting-started.md
    - System Reference: system.md
  - Reference: 
    - reference/index.md
    - reference/routes.md
    - reference/services.md
    - reference/repository.md
    - reference/spider.md
  - openapi.md